version: "3.9"

services:
  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
  redis:
    image: redis:alpine
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis


