# Generated by Django 3.2.4 on 2021-06-18 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Branches', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tree.tree')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
