# Generated by Django 3.1.6 on 2021-06-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20210619_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ('published',)},
        ),
    ]
